/**
 * src/main.jsx
 *
 * Application entry point — the first JavaScript file executed by the browser
 * after Vite bundles and serves the app.
 *
 * # ReactDOM.createRoot (React 18+ Concurrent Mode)
 *
 *   ReactDOM.createRoot(domNode) replaces the legacy ReactDOM.render() call
 *   from React 17 and earlier. The key difference is that createRoot enables
 *   React's "concurrent mode", which allows React to pause, interrupt, and
 *   restart rendering work. This unlocks features like startTransition and
 *   Suspense streaming — though the task queue UI doesn't use them directly,
 *   createRoot is the correct default for all new React 18 projects.
 *
 * # React.StrictMode
 *
 *   StrictMode is a development-only wrapper that:
 *     - Double-invokes component functions and useEffect callbacks (mount →
 *       unmount → remount) to surface non-idempotent side effects.
 *     - Warns about deprecated APIs.
 *
 *   There is no production cost: StrictMode renders are stripped in the
 *   production build by Vite/React. If you notice Dashboard's polling
 *   useEffect fires twice on mount in development, that is StrictMode at work,
 *   not a bug.
 *
 * # Error boundary fallback
 *
 *   The try/catch around createRoot is a last-resort error display. React's
 *   own error boundaries (componentDidCatch) catch errors inside the React
 *   tree, but errors thrown DURING the initial render before React has mounted
 *   (e.g. missing DOM node, corrupted bundle) bypass those boundaries.
 *   The catch block writes a plain-HTML diagnostic panel directly into the
 *   #root div so the user sees a message instead of a blank white page.
 *
 *   Note: `${error.message}` and `${error.stack}` are evaluated at the time
 *   the error is caught, so they reflect the actual failure.
 */
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'   // Tailwind base + component layers generated by Vite

try {
  // Mount the React tree into the <div id="root"> in index.html.
  // createRoot returns a root object; root.render() is called once here.
  const root = ReactDOM.createRoot(document.getElementById('root'))
  root.render(
    // StrictMode adds development-time checks — zero production cost.
    <React.StrictMode>
      <App />
    </React.StrictMode>
  )
} catch (error) {
  // If React itself fails to initialise (corrupted bundle, missing DOM node,
  // etc.), surface the error as plain HTML so the user isn't staring at
  // a blank screen with no indication of what went wrong.
  console.error('Failed to render app:', error)
  document.getElementById('root').innerHTML = `
    <div style="padding: 20px; font-family: sans-serif;">
      <h1>Error Loading App</h1>
      <p>${error.message}</p>
      <pre>${error.stack}</pre>
    </div>
  `
}

